# afucosylation () on 1E4K
# Generated by fcatlas (Fc Variant Atlas). Reproducible: no timestamps.
#
# Structure : 1E4K - FcgammaRIIIb ectodomain
# Fc chains : A+B
# Fc genotype in this entry: wild type
#
# Run with:  pymol afucosylated_1E4K.pml
# PyMOL fetches the structure over the network on first run.

reinitialize
set fetch_type_default, cif
set assembly, 1
fetch 1E4K, async=0
hide everything
bg_color white
set cartoon_transparency, 0.15
set ray_opaque_background, 0

select fc, 1E4K and chain A+B and polymer
select partner, 1E4K and chain C and polymer
show cartoon, fc or partner
color grey90, fc
color grey70, partner

# measured interface, 5.0 A heavy-atom cutoff
select interface, fc and resi 234+235+236+237+238+239+265+266+267+269+297+298+299+326+327+328+329+330+332
color palecyan, interface
show sticks, interface and not (name C+N+O)
set stick_radius, 0.15, interface

# afucosylation carries no substitutions: GLYCAN VARIANT, NOT A SEQUENCE VARIANT. It carries no substitutions an
orient interface

set antialias, 2
set ray_shadows, 0
deselect
