# N297G (N297G) on 1E4K
# Generated by fcatlas (Fc Variant Atlas). Reproducible: no timestamps.
#
# Structure : 1E4K - FcgammaRIIIb ectodomain
# Fc chains : A+B
# Fc genotype in this entry: wild type
#
# Run with:  pymol N297G_1E4K.pml
# PyMOL fetches the structure over the network on first run.

reinitialize
set fetch_type_default, cif
set assembly, 1
fetch 1E4K, async=0
hide everything
bg_color white
set cartoon_transparency, 0.15
set ray_opaque_background, 0

select fc, 1E4K and chain A+B and polymer
select partner, 1E4K and chain C and polymer
show cartoon, fc or partner
color grey90, fc
color grey70, partner

# measured interface, 5.0 A heavy-atom cutoff
select interface, fc and resi 234+235+236+237+238+239+265+266+267+269+297+298+299+326+327+328+329+330+332
color palecyan, interface
show sticks, interface and not (name C+N+O)
set stick_radius, 0.15, interface

# N297G: N297G
select variant, fc and resi 297
color red, variant
show spheres, variant and not hydrogens
set sphere_scale, 0.30, variant
show sticks, variant
set stick_radius, 0.25, variant
label variant and name CA, '%s%s' % (one_letter[resn], resi)
set label_size, 16
set label_color, black
set label_outline_color, white

# variant positions inside the measured interface: 297
select variant_at_interface, fc and resi 297
distance contacts, variant_at_interface, partner, 5.0, mode=0
color black, contacts
set dash_gap, 0.3
hide labels, contacts

# report unresolved positions to the log
python
wanted = [297]
present = set()
cmd.iterate('fc and name CA', 'present.add(int(resi))', space={'present': present, 'int': int})
missing = [p for p in wanted if p not in present]
print('fcatlas: variant positions not resolved in this model:', missing if missing else 'none')
python end

orient variant or (interface within 12 of variant)

set antialias, 2
set ray_shadows, 0
deselect
