# afucosylation () on 4N0U
# Generated by fcatlas (Fc Variant Atlas). Reproducible: no timestamps.
#
# Structure : 4N0U - FcRn heavy chain and beta-2 microglobulin
# Fc chains : E
# Fc genotype in this entry: M252Y/S254T/T256E (YTE)
# CAVEAT  : This Fc is not wild type. The three YTE substitutions sit inside the FcRn contact patch, so contact distances at EU 252, 254 and 256 describe the engineered molecule, not human IgG1.
#
# Run with:  pymol afucosylated_4N0U.pml
# PyMOL fetches the structure over the network on first run.

reinitialize
set fetch_type_default, cif
set assembly, 1
fetch 4N0U, async=0
hide everything
bg_color white
set cartoon_transparency, 0.15
set ray_opaque_background, 0

select fc, 4N0U and chain E and polymer
select partner, 4N0U and chain A+B and polymer
show cartoon, fc or partner
color grey90, fc
color grey70, partner

# measured interface, 5.0 A heavy-atom cutoff
select interface, fc and resi 251+252+253+254+257+285+288+307+308+309+310+311+433+434+435+436
color palecyan, interface
show sticks, interface and not (name C+N+O)
set stick_radius, 0.15, interface

# afucosylation carries no substitutions: GLYCAN VARIANT, NOT A SEQUENCE VARIANT. It carries no substitutions an
orient interface

set antialias, 2
set ray_shadows, 0
deselect
