# IgG4 PAA (S228P/F234A/L235A) on 4N0U
# Generated by fcatlas (Fc Variant Atlas). Reproducible: no timestamps.
#
# Structure : 4N0U - FcRn heavy chain and beta-2 microglobulin
# Fc chains : E
# Fc genotype in this entry: M252Y/S254T/T256E (YTE)
# CAVEAT  : This Fc is not wild type. The three YTE substitutions sit inside the FcRn contact patch, so contact distances at EU 252, 254 and 256 describe the engineered molecule, not human IgG1.
#
# Run with:  pymol IgG4-PAA_4N0U.pml
# PyMOL fetches the structure over the network on first run.

reinitialize
set fetch_type_default, cif
set assembly, 1
fetch 4N0U, async=0
hide everything
bg_color white
set cartoon_transparency, 0.15
set ray_opaque_background, 0

select fc, 4N0U and chain E and polymer
select partner, 4N0U and chain A+B and polymer
show cartoon, fc or partner
color grey90, fc
color grey70, partner

# measured interface, 5.0 A heavy-atom cutoff
select interface, fc and resi 251+252+253+254+257+285+288+307+308+309+310+311+433+434+435+436
color palecyan, interface
show sticks, interface and not (name C+N+O)
set stick_radius, 0.15, interface

# IgG4 PAA: S228P/F234A/L235A
select variant, fc and resi 228+234+235
color red, variant
show spheres, variant and not hydrogens
set sphere_scale, 0.30, variant
show sticks, variant
set stick_radius, 0.25, variant
label variant and name CA, '%s%s' % (one_letter[resn], resi)
set label_size, 16
set label_color, black
set label_outline_color, white

# none of this variant's positions contact the partner in this
# structure, so any effect it has is not a direct steric block here

# report unresolved positions to the log
python
wanted = [228, 234, 235]
present = set()
cmd.iterate('fc and name CA', 'present.add(int(resi))', space={'present': present, 'int': int})
missing = [p for p in wanted if p not in present]
print('fcatlas: variant positions not resolved in this model:', missing if missing else 'none')
python end

orient variant or (interface within 12 of variant)

set antialias, 2
set ray_shadows, 0
deselect
